apiVersion: v1
kind: Service
metadata:
  name: logstashrmq
  labels:
    name: logstashrmq
spec:
  type: NodePort
  ports:
  - name: logstashinput
    port: 5044
    targetPort: 5044
    protocol: TCP
  selector:
    name: logstashrmq
